// <auto-generated />
using System;
using ETB.WebApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ETB.WebApi.Migrations
{
    [DbContext(typeof(ETBContext))]
    partial class ETBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ETB.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DeptBelongsTo")
                        .HasMaxLength(50);

                    b.Property<string>("Deptartment")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ETB.Core.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DistrictHQ")
                        .HasMaxLength(50);

                    b.Property<string>("DistrictName")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DistrictHQ = "Araria",
                            DistrictName = "Araria",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 102,
                            DistrictHQ = "Arwal",
                            DistrictName = "Arwal",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 103,
                            DistrictHQ = "Aurangabad",
                            DistrictName = "Aurangabad",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 104,
                            DistrictHQ = "Banka",
                            DistrictName = "Banka",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 105,
                            DistrictHQ = "Begusarai",
                            DistrictName = "Begusarai",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 106,
                            DistrictHQ = "Bhabhua",
                            DistrictName = "Bhabhua",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 107,
                            DistrictHQ = "Bhagalpur",
                            DistrictName = "Bhagalpur",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 108,
                            DistrictHQ = "Ara",
                            DistrictName = "Bhojpur",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 109,
                            DistrictHQ = "Buxar",
                            DistrictName = "Buxar",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 110,
                            DistrictHQ = "Darbhanga",
                            DistrictName = "Darbhanga",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 111,
                            DistrictHQ = "Motihari",
                            DistrictName = "East Champaran",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 112,
                            DistrictHQ = "Gaya",
                            DistrictName = "Gaya",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 113,
                            DistrictHQ = "Gopalganj",
                            DistrictName = "Gopalganj",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 114,
                            DistrictHQ = "Jamui",
                            DistrictName = "Jamui",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 115,
                            DistrictHQ = "Jehanabad",
                            DistrictName = "Jehanabad",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 116,
                            DistrictHQ = "Katihar",
                            DistrictName = "Katihar",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 117,
                            DistrictHQ = "Khagaria",
                            DistrictName = "Khagaria",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 118,
                            DistrictHQ = "Kishanganj",
                            DistrictName = "Kishanganj",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 119,
                            DistrictHQ = "Lakhisarai",
                            DistrictName = "Lakhisarai",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 120,
                            DistrictHQ = "Madhepura",
                            DistrictName = "Madhepura",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 121,
                            DistrictHQ = "Madhubani",
                            DistrictName = "Madhubani",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 122,
                            DistrictHQ = "Munger",
                            DistrictName = "Munger",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 123,
                            DistrictHQ = "Muzaffarpur ",
                            DistrictName = "Muzaffarpur",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 124,
                            DistrictHQ = "Nalanda ",
                            DistrictName = "Nalanda",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 125,
                            DistrictHQ = "Nawada ",
                            DistrictName = "Nawada",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 126,
                            DistrictHQ = "Patna",
                            DistrictName = "Patna",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 127,
                            DistrictHQ = "Purnea ",
                            DistrictName = "Purnea",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 128,
                            DistrictHQ = "Sasaram",
                            DistrictName = "Rohtas",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 129,
                            DistrictHQ = "Saharsa ",
                            DistrictName = "Saharsa",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 130,
                            DistrictHQ = "Samastipur ",
                            DistrictName = "Samastipur",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 131,
                            DistrictHQ = "Chapra",
                            DistrictName = "Saran",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 132,
                            DistrictHQ = "Sheikhpura",
                            DistrictName = "Sheikhpura",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 133,
                            DistrictHQ = "Sheohar",
                            DistrictName = "Sheohar",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 134,
                            DistrictHQ = "Sitamarhi",
                            DistrictName = "Sitamarhi",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 135,
                            DistrictHQ = "Siwan",
                            DistrictName = "Siwan",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 136,
                            DistrictHQ = "Supaul",
                            DistrictName = "Supaul",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 137,
                            DistrictHQ = "Hajipur",
                            DistrictName = "Vaishali",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 138,
                            DistrictHQ = "Bettiah",
                            DistrictName = "West Champaran",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 1001,
                            DistrictHQ = "Bokaro",
                            DistrictName = "Bokaro",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1002,
                            DistrictHQ = "Chatra",
                            DistrictName = "Chatra",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1003,
                            DistrictHQ = "Deoghar",
                            DistrictName = "Deoghar",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1004,
                            DistrictHQ = "Dhanbad",
                            DistrictName = "Dhanbad",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1005,
                            DistrictHQ = "Dumka",
                            DistrictName = "Dumka",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1006,
                            DistrictHQ = "Jamshedpur",
                            DistrictName = "East Singhbhum",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1007,
                            DistrictHQ = "Garhwa",
                            DistrictName = "Garhwa",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1008,
                            DistrictHQ = "Giridih",
                            DistrictName = "Giridih",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1009,
                            DistrictHQ = "Godda",
                            DistrictName = "Godda",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1010,
                            DistrictHQ = "Gumla",
                            DistrictName = "Gumla",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1011,
                            DistrictHQ = "Hazaribag",
                            DistrictName = "Hazaribagh",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1012,
                            DistrictHQ = "Jamtara",
                            DistrictName = "Jamtara",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1013,
                            DistrictHQ = "Khunti",
                            DistrictName = "Khunti",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1014,
                            DistrictHQ = "Koderma",
                            DistrictName = "Kodarma",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1015,
                            DistrictHQ = "Latehar",
                            DistrictName = "Latehar",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1016,
                            DistrictHQ = "Lohardaga",
                            DistrictName = "Lohardaga",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1017,
                            DistrictHQ = "Pakur",
                            DistrictName = "Pakur",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1018,
                            DistrictHQ = "Daltonganj",
                            DistrictName = "Palamu",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1019,
                            DistrictHQ = "Ramgarh",
                            DistrictName = "Ramgarh",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1020,
                            DistrictHQ = "Ranchi",
                            DistrictName = "Ranchi",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1021,
                            DistrictHQ = "Sahebganj",
                            DistrictName = "Sahibganj",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1022,
                            DistrictHQ = "Seraikela",
                            DistrictName = "Saraikela Kharsawan",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1023,
                            DistrictHQ = "Simdega",
                            DistrictName = "Simdega",
                            State = "Jharkhand"
                        },
                        new
                        {
                            Id = 1024,
                            DistrictHQ = "Chaibasa",
                            DistrictName = "West Singhbhum",
                            State = "Jharkhand"
                        });
                });

            modelBuilder.Entity("ETB.Core.Entities.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Deptartment")
                        .HasMaxLength(100);

                    b.Property<string>("DistrictName")
                        .HasMaxLength(50);

                    b.Property<string>("DivisionName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("ETB.Core.Entities.ExternalContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(255);

                    b.Property<string>("City");

                    b.Property<string>("Class")
                        .HasMaxLength(10);

                    b.Property<string>("ContactNo1")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("District")
                        .HasMaxLength(50);

                    b.Property<string>("Email1")
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .HasMaxLength(100);

                    b.Property<string>("Organisation")
                        .HasMaxLength(100);

                    b.Property<string>("Others")
                        .HasMaxLength(255);

                    b.Property<string>("PAN")
                        .HasMaxLength(10);

                    b.Property<string>("Salutation")
                        .HasMaxLength(10);

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ExternalContacts");
                });

            modelBuilder.Entity("ETB.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<int>("Duration");

                    b.Property<int>("IsActive");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price");

                    b.Property<string>("ServiceRepUrl")
                        .HasMaxLength(255);

                    b.Property<int>("ServiceType");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ETB.Core.Entities.ServiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Detail")
                        .HasMaxLength(100);

                    b.Property<int?>("ServiceId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceDetails");
                });

            modelBuilder.Entity("ETB.Core.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capital")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("StateOrOthers");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = "Patna",
                            Name = "Bihar",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 2,
                            Capital = "Hyderabad",
                            Name = "Andhra Pradesh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 3,
                            Capital = "Itanagar",
                            Name = "Arunachal Pradesh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 4,
                            Capital = "Dispur",
                            Name = "Assam",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 5,
                            Capital = "Raipur",
                            Name = "Chhattisgarh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 6,
                            Capital = "Panaji",
                            Name = "Goa",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 7,
                            Capital = "Gandhinagar",
                            Name = "Gujarat",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 8,
                            Capital = "Chandigarh",
                            Name = "Haryana",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 9,
                            Capital = "Shimla",
                            Name = "Himachal Pradesh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 10,
                            Capital = "Ranchi",
                            Name = "Jharkhand",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 11,
                            Capital = "Bengaluru",
                            Name = "Karnataka",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 12,
                            Capital = "Thiruvananthapuram",
                            Name = "Kerala",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 13,
                            Capital = "Bhopal",
                            Name = "Madhya Pradesh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 14,
                            Capital = "Mumbai",
                            Name = "Maharashtra",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 15,
                            Capital = "Imphal",
                            Name = "Manipur",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 16,
                            Capital = "Shillong",
                            Name = "Meghalaya",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 17,
                            Capital = "Aizawl",
                            Name = "Mizoram",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 18,
                            Capital = "Kohima",
                            Name = "Nagaland",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 19,
                            Capital = "Bhubaneswar",
                            Name = "Odisha",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 20,
                            Capital = "Chandigarh",
                            Name = "Punjab",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 21,
                            Capital = "Jaipur",
                            Name = "Rajasthan",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 22,
                            Capital = "Gangtok",
                            Name = "Sikkim",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 23,
                            Capital = "Chennai",
                            Name = "Tamil Nadu",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 24,
                            Capital = "Hyderabad",
                            Name = "Telangana",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 25,
                            Capital = "Agartala",
                            Name = "Tripura",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 26,
                            Capital = "Lucknow",
                            Name = "Uttar Pradesh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 27,
                            Capital = "Dehradun",
                            Name = "Uttarakhand",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 28,
                            Capital = "Kolkata",
                            Name = "West Bengal",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 29,
                            Capital = "Port Blair",
                            Name = "Andaman and Nicobar Islands",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 30,
                            Capital = "Chandigarh",
                            Name = "Chandigarh",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 31,
                            Capital = "Silvassa",
                            Name = "Dadar and Nagar Haveli",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 32,
                            Capital = "Daman",
                            Name = "Daman and Diu",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 33,
                            Capital = "Delhi",
                            Name = "Delhi",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 34,
                            Capital = "Kavaratti",
                            Name = "Lakshadweep",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 35,
                            Capital = "Pondicherry",
                            Name = "Puducherry (Pondicherry)",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 36,
                            Capital = "Srinagar",
                            Name = "Jammu and Kashmir",
                            StateOrOthers = 0
                        },
                        new
                        {
                            Id = 37,
                            Capital = "Leh",
                            Name = "Ladakh",
                            StateOrOthers = 0
                        });
                });

            modelBuilder.Entity("ETB.Core.Entities.Tender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankCertificate");

                    b.Property<DateTime>("BidOpeningDate");

                    b.Property<DateTime>("BidSubmissionEnDate");

                    b.Property<DateTime?>("BidSubmissionStDate");

                    b.Property<string>("COT");

                    b.Property<decimal>("CostOfBOQ");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("Currency");

                    b.Property<string>("Department")
                        .HasMaxLength(150);

                    b.Property<string>("DescOfWork");

                    b.Property<string>("District")
                        .HasMaxLength(100);

                    b.Property<string>("Division")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DocumentDownloadEdDate");

                    b.Property<DateTime?>("DocumentDownloadStDate");

                    b.Property<decimal>("EMD");

                    b.Property<string>("EMDPayableAt")
                        .HasMaxLength(70);

                    b.Property<string>("EMDPaymentOption")
                        .HasMaxLength(50);

                    b.Property<decimal>("EstimatedCost");

                    b.Property<int>("IsActive");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("NIT")
                        .HasMaxLength(100);

                    b.Property<string>("Organisation")
                        .HasMaxLength(150);

                    b.Property<int>("ParentTenderId");

                    b.Property<string>("PayableAt")
                        .HasMaxLength(70);

                    b.Property<int>("PaymentOption");

                    b.Property<int>("PublishOrLive");

                    b.Property<string>("Region")
                        .HasMaxLength(100);

                    b.Property<string>("TenderDocument")
                        .HasMaxLength(250);

                    b.Property<string>("TenderRef")
                        .HasMaxLength(100);

                    b.Property<string>("TenderRefSiteAddress")
                        .HasMaxLength(250);

                    b.Property<string>("TenderTitle")
                        .HasMaxLength(150);

                    b.Property<string>("TenderType");

                    b.Property<int>("UnEmployedEng");

                    b.Property<string>("ValueFactor")
                        .HasMaxLength(25);

                    b.Property<string>("WorkNo")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ePublishDate");

                    b.HasKey("Id");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("ETB.Core.Entities.TenderDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocFor");

                    b.Property<string>("DocName")
                        .HasMaxLength(50);

                    b.Property<string>("DocPath")
                        .HasMaxLength(255);

                    b.Property<int?>("TenderId");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderDocs");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(150);

                    b.Property<int>("Age");

                    b.Property<string>("City")
                        .HasMaxLength(75);

                    b.Property<string>("ContactNo1")
                        .HasMaxLength(20);

                    b.Property<string>("ContactNo2Mobile")
                        .HasMaxLength(20);

                    b.Property<string>("ContactNo3Mobile")
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("DOB");

                    b.Property<string>("District")
                        .HasMaxLength(50);

                    b.Property<string>("Email1")
                        .HasMaxLength(100);

                    b.Property<string>("Email2Optinal")
                        .HasMaxLength(100);

                    b.Property<string>("FName")
                        .HasMaxLength(50);

                    b.Property<int>("Gender");

                    b.Property<int>("IsActive");

                    b.Property<int>("IsDetailUpdated");

                    b.Property<string>("LName")
                        .HasMaxLength(50);

                    b.Property<string>("MName")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Nationality")
                        .HasMaxLength(25);

                    b.Property<string>("Organisation")
                        .HasMaxLength(100);

                    b.Property<string>("PanNo")
                        .HasMaxLength(15);

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255);

                    b.Property<string>("Pin");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(50);

                    b.Property<string>("Salutation")
                        .HasMaxLength(10);

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.Property<int?>("UserInfoId");

                    b.Property<int>("WantEmailNotfi");

                    b.Property<int>("WantSMSNotfi");

                    b.Property<int>("WantWhatsUpNotfi");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Allow");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("Pass")
                        .HasMaxLength(255);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<int>("UserRole");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmtReceived");

                    b.Property<decimal>("AmtReceivedDate");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("IsServiceInForce");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<decimal>("OriginalAmt");

                    b.Property<DateTime>("ServiceEnDate");

                    b.Property<int>("ServiceId");

                    b.Property<DateTime>("ServiceStDate");

                    b.Property<int>("UserDetailId");

                    b.HasKey("Id");

                    b.ToTable("UserServices");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserSignInLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SignInTime");

                    b.Property<int>("SignInType");

                    b.Property<int?>("UserInfoId");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("UserSignInLogs");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("ExtendedEndDate");

                    b.Property<int>("IsActive");

                    b.Property<bool>("IsPaid");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<int>("PayingMethod");

                    b.Property<int?>("ServiceId");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("UserDetailId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserDetailId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("ETB.Core.Entities.ServiceDetail", b =>
                {
                    b.HasOne("ETB.Core.Entities.Service")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("ETB.Core.Entities.TenderDoc", b =>
                {
                    b.HasOne("ETB.Core.Entities.Tender")
                        .WithMany("TenderDocs")
                        .HasForeignKey("TenderId");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserDetail", b =>
                {
                    b.HasOne("ETB.Core.Entities.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserSignInLog", b =>
                {
                    b.HasOne("ETB.Core.Entities.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("ETB.Core.Entities.UserSubscription", b =>
                {
                    b.HasOne("ETB.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("ETB.Core.Entities.UserDetail", "UserDetail")
                        .WithMany()
                        .HasForeignKey("UserDetailId");
                });
#pragma warning restore 612, 618
        }
    }
}
